### ISSUE TITLE
Limit multipliers in cycles?

### ISSUE THREAD

**Issue by emuell** [emuell/afseq#9]
It's currently possible to specify very high multiplier values in cycles, such as:

``cycle("c4*10000")``

This is a valid notation, but will easily cause audio dropouts or even out-of-memory panics in extreme cases.

The out-of-memory problem will also occur, but not only, because entire cycles are generated and consumed in one go via Cycle::generate(). 
   
@unlessgames 
Probably we should limit all these multiplies to some "healthy" values like 100 and spit out parser errors for everything above,
 just to avoid crashes and user errors?

**Comment by unlessgames** [comment]
Hmm. I guess, although I am not entirely against letting the user test their system's limits if they so please.

The more technical problem I see is that since nesting is possible, it's not as trivial to limit the multiplier. For example `[[a*100]*100, b]*100` obeys the 100 clamp rule but results in a huge list.

**Comment by emuell** [comment]
> For example [[a*100 b]*100 b]*100 obeys the 100 clamp rule but results in a huge list.

Good point. What about limiting the total number of events generated per cycle? Let's say 1024*128?
Surely anything above that can't be generated in real time. The cycle would not need to count the steps before generating, just check them during generation. 

This would be similar to how Lua timeouts work. Currently a Lua script or function callback has 200ms to run. If it runs longer, it will abort with an error to avoid deallocks.
